apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx-app
  template:
    metadata:
      labels:
        app: my-nginx-app
    spec:
      serviceAccountName: my-app-sa  # 👈 attaches the SA here
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

