apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    app: demo1
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: root
    ports:
    - containerPort: 3306
---
apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    app: demo2
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

